//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IT_Center.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ITCenterEntities : DbContext
    {
        public ITCenterEntities()
            : base("name=ITCenterEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Client> Client { get; set; }
        public virtual DbSet<Detail> Detail { get; set; }
        public virtual DbSet<DetailOfOrder> DetailOfOrder { get; set; }
        public virtual DbSet<Employee> Employee { get; set; }
        public virtual DbSet<Order> Order { get; set; }
        public virtual DbSet<Product> Product { get; set; }
        public virtual DbSet<ProductOfSale> ProductOfSale { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<Sale> Sale { get; set; }
        public virtual DbSet<Service> Service { get; set; }
        public virtual DbSet<ServiceOfOrder> ServiceOfOrder { get; set; }
        public virtual DbSet<ServiceOfOrderStatus> ServiceOfOrderStatus { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TypeOfDetail> TypeOfDetail { get; set; }
        public virtual DbSet<TypeOfProduct> TypeOfProduct { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
