//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IT_Center.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Detail()
        {
            this.DetailOfOrder = new HashSet<DetailOfOrder>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int TypeOfDetailId { get; set; }
        public decimal Price { get; set; }
        public string Description { get; set; }
        public byte[] Photo { get; set; }
    
        public virtual TypeOfDetail TypeOfDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetailOfOrder> DetailOfOrder { get; set; }
    }
}
